import {aiReadinessFixture} from './activation-fixture'
import React from 'react';import {it,expect,vi,afterEach} from 'vitest';import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';import AIDraftSetup from '../src/AIDraftSetup';
afterEach(cleanup);
const config={schema_version:1,provider:'openai',model:'fixture',task:'customer_reply',instructions:'Use the supplied facts for a draft.',source:'manual_context',max_input_bytes:6000,max_output_tokens:1000,max_daily_runs:10,daily_budget_microusd:1000000,human_review:true};
const saved={id:'config-id',version:1,configuration:config};const loaded={configuration:saved,runs:[],unresolved_count:0,catalog:[{provider:'openai',model:'fixture',available:true,structured_outputs:true}],readiness:aiReadinessFixture('org','config-id')};
const make=fn=>({functions:{invoke:vi.fn(async(_,{body})=>({data:await fn(body)}))}});
const ready=async(client)=>{render(<AIDraftSetup organizationId="org" client={client}/>);await screen.findByText(/version 1/);fireEvent.change(screen.getByLabelText('Business context'),{target:{value:'Synthetic business facts only.'}})};
it('unconfigured workspace can save versioned setup, cannot infer',async()=>{const client=make(b=>b.operation==='load'?{...loaded,readiness:{live_enabled:false,credential_configured:false,status:'provider_unconfigured'}}:{configuration:{...saved,version:2,configuration:b.configuration}});await ready(client);expect(screen.getByText('Generate review-only draft').disabled).toBe(true);fireEvent.change(screen.getByLabelText('Task instructions'),{target:{value:'Prepare a concise customer reply.'}});fireEvent.click(screen.getByText('Save configuration version'));await screen.findByText(/Configuration version 2 saved/);expect(client.functions.invoke.mock.calls.at(-1)[1].body.expected_version).toBe(1)});
it('full setup to mock draft to human acceptance preserves explicit review',async()=>{const r={id:'run',status:'awaiting_review',reserved_microusd:1234,usage:{input_tokens:4,output_tokens:8},draft:{title:'Customer reply',body:'Synthetic draft body.',source_ids:['manual-1'],warnings:['Check the date.']}};const client=make(b=>b.operation==='load'?loaded:b.operation==='run'?{run:r}:{run:{...r,status:b.decision}});await ready(client);fireEvent.click(screen.getByText('Generate review-only draft'));await screen.findByText('Synthetic draft body.');expect(screen.getByText(/Observed tokens/).textContent).toContain('4 input / 8 output');expect(screen.getByText(/Accepting records your review/)).not.toBeNull();fireEvent.click(screen.getByText('Accept draft for use'));await screen.findByText(/Status: accepted/);expect(client.functions.invoke.mock.calls.at(-1)[1].body.operation).toBe('review')});
it('double clicks cause one model request and dirty config blocks run',async()=>{let resolve;const client=make(b=>b.operation==='load'?loaded:new Promise(r=>{resolve=r}));await ready(client);fireEvent.change(screen.getByLabelText('Task instructions'),{target:{value:'A changed task instruction.'}});expect(screen.getByText('Generate review-only draft').disabled).toBe(true);cleanup();await ready(client);const button=screen.getByText('Generate review-only draft');fireEvent.click(button);fireEvent.click(button);expect(client.functions.invoke.mock.calls.filter(x=>x[1].body.operation==='run')).toHaveLength(1);resolve({run:{id:'r',status:'failed',reserved_microusd:1000,failure_code:'provider_refused'}});await screen.findByText(/provider_refused/)});
it('unknown transport then reserved reconciliation never unlocks replacement',async()=>{let count=0;const client={functions:{invoke:vi.fn(async(_,{body})=>{if(body.operation==='run')return {error:new Error('transport')};count++;return {data:count===1?loaded:{...loaded,unresolved_count:1,runs:[{id:'r',request_key:client.functions.invoke.mock.calls.find(x=>x[1].body.operation==='run')[1].body.request_key,status:'reserved',reserved_microusd:1000}]}}})}};await ready(client);fireEvent.click(screen.getByText('Generate review-only draft'));await screen.findByText(/A request is unresolved/);fireEvent.click(screen.getByText('Check recorded outcome'));await screen.findByText(/Recorded run status: reserved/);expect(screen.getByText('Generate review-only draft').disabled).toBe(true)});
it('unknown run outside visible history blocks new inference',async()=>{await ready(make(()=>({...loaded,unresolved_count:1})));expect(screen.getByText('Generate review-only draft').disabled).toBe(true);expect(screen.getByText('Check recorded outcome')).not.toBeNull()});
it('organization switch discards late response and wrong-org draft',async()=>{let resolve;const client=make(b=>b.organization_id==='first'?new Promise(r=>{resolve=r}):loaded);const view=render(<AIDraftSetup organizationId="first" client={client}/>);view.rerender(<AIDraftSetup organizationId="second" client={client}/>);await screen.findByText(/version 1/);resolve({...loaded,configuration:{...saved,version:88}});await waitFor(()=>expect(screen.queryByText(/version 88/)).toBeNull())});
