import React, {useEffect,useState} from 'react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
const api=vi.hoisted(()=>({invoke:vi.fn(),from:vi.fn(),rpc:vi.fn(),getSession:vi.fn(),onAuthStateChange:vi.fn(),signOut:vi.fn()}))
vi.mock('../src/supabase',()=>({supabase:{functions:{invoke:api.invoke},from:api.from,rpc:api.rpc,auth:{getSession:api.getSession,onAuthStateChange:api.onAuthStateChange,signOut:api.signOut}}}))
vi.mock('../src/CustomerReplyWorkspace',()=>({default:function Fixture({org,session,onDirtyChange,onBusyChange}){const [text,setText]=useState('');useEffect(()=>()=>{onDirtyChange(false);onBusyChange(false)},[onDirtyChange,onBusyChange]);return <section><p>{org.id}:{session.user.id}</p><label>Fixture draft<input value={text} onChange={e=>{setText(e.target.value);onDirtyChange(!!e.target.value)}}/></label><button onClick={()=>onBusyChange(true)}>Fixture start</button><button onClick={()=>onBusyChange(false)}>Fixture finish</button></section>}}))
import {App} from '../src/main'
let emit
beforeEach(()=>{
 window.history.replaceState({},'','/app/?kairoCompany=company-a#Customer%20Follow-up')
 api.signOut.mockReset();api.from.mockReset();api.invoke.mockReset();api.rpc.mockReset()
 api.getSession.mockResolvedValue({data:{session:{user:{id:'owner-a'},access_token:'synthetic'}}})
 api.onAuthStateChange.mockImplementation(callback=>{emit=callback;return {data:{subscription:{unsubscribe:vi.fn()}}}})
 api.invoke.mockResolvedValue({data:{members:[]},error:null})
 api.from.mockImplementation(table=>{let single=false;const result=()=>({data:table==='organizations'?[{id:'company-a',name:'Company A'},{id:'company-b',name:'Company B'}]:single?null:[],error:null});const q={select:()=>q,eq:()=>q,order:()=>q,limit:()=>q,maybeSingle:()=>{single=true;return Promise.resolve(result())},then:(resolve,reject)=>Promise.resolve(result()).then(resolve,reject)};return q})
 vi.spyOn(window,'confirm').mockReturnValue(false)
})
afterEach(()=>{cleanup();vi.restoreAllMocks();window.history.replaceState({},'','/');window.sessionStorage.clear()})
async function open(){const view=render(<App/>);await screen.findByLabelText('Fixture draft');return view}
it('opens a direct customer-workspace link with verified company/account scope',async()=>{await open();expect(screen.getByRole('heading',{level:1,name:'Customer Follow-up'})).toBeTruthy();expect(screen.getByText('company-a:owner-a')).toBeTruthy()})
it('blocks section navigation and sign out when an unsaved inquiry is kept',async()=>{await open();fireEvent.change(screen.getByLabelText('Fixture draft'),{target:{value:'keep me'}});fireEvent.click(screen.getByRole('button',{name:'Overview'}));expect(screen.getByLabelText('Fixture draft').value).toBe('keep me');fireEvent.click(screen.getByRole('button',{name:'Sign out'}));expect(api.signOut).not.toHaveBeenCalled();expect(window.location.hash).toBe('#Customer%20Follow-up')})
it('protects company switches and discards only after explicit confirmation',async()=>{const view=await open();fireEvent.change(screen.getByLabelText('Fixture draft'),{target:{value:'keep me'}});const companies=view.container.querySelector('.org-switcher select');fireEvent.change(companies,{target:{value:'company-b'}});expect(screen.getByText('company-a:owner-a')).toBeTruthy();expect(companies.value).toBe('company-a');window.confirm.mockReturnValue(true);fireEvent.change(companies,{target:{value:'company-b'}});await screen.findByText('company-b:owner-a');expect(screen.getByLabelText('Fixture draft').value).toBe('')})
it('keeps active operations mounted and blocks company changes and sign out',async()=>{const view=await open();fireEvent.click(screen.getByRole('button',{name:'Fixture start'}));expect(view.container.querySelector('.org-switcher select').disabled).toBe(true);expect(screen.getByRole('button',{name:'Sign out'}).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Overview'}));expect(screen.getByLabelText('Fixture draft')).toBeTruthy();expect(window.confirm).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Fixture finish'}));fireEvent.click(screen.getByRole('button',{name:'Overview'}));await screen.findByRole('heading',{level:1,name:'Overview'})})
it('preserves draft on token refresh and resets on account change',async()=>{await open();fireEvent.change(screen.getByLabelText('Fixture draft'),{target:{value:'current draft'}});await act(async()=>emit('TOKEN_REFRESHED',{user:{id:'owner-a'},access_token:'new'}));expect(screen.getByLabelText('Fixture draft').value).toBe('current draft');await act(async()=>emit('SIGNED_IN',{user:{id:'owner-b'},access_token:'other'}));await waitFor(()=>expect(screen.getByText('company-a:owner-b')).toBeTruthy());expect(screen.getByLabelText('Fixture draft').value).toBe('')})
it('preserves dirty customer work across cancelled browser Back and then allows confirmed navigation',async()=>{
 window.history.replaceState({},'','/app/?kairoCompany=company-a#Overview');render(<App/>);await screen.findByRole('heading',{level:1,name:'Overview'});fireEvent.click(screen.getByRole('button',{name:'Customer Follow-up'}));await screen.findByLabelText('Fixture draft');fireEvent.change(screen.getByLabelText('Fixture draft'),{target:{value:'keep across back'}});const length=window.history.length;await act(async()=>{window.history.back();await new Promise(r=>setTimeout(r,40))});await waitFor(()=>expect(window.location.hash).toBe('#Customer%20Follow-up'));expect(screen.getByLabelText('Fixture draft').value).toBe('keep across back');expect(window.history.length).toBe(length);window.confirm.mockReturnValue(true);await act(async()=>{window.history.back();await new Promise(r=>setTimeout(r,40))});await screen.findByRole('heading',{level:1,name:'Overview'});expect(window.location.search).toBe('?kairoCompany=company-a')
})
it('protects a dirty request during a same-section browser company change',async()=>{
 await open();fireEvent.change(screen.getByLabelText('Fixture draft'),{target:{value:'company a only'}});window.history.replaceState({},'','/app/?kairoCompany=company-b#Customer%20Follow-up');fireEvent.popState(window);expect(screen.getByText('company-a:owner-a')).toBeTruthy();expect(screen.getByLabelText('Fixture draft').value).toBe('company a only');expect(window.location.search).toBe('?kairoCompany=company-a')
})
