import React from 'react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
vi.mock('../src/supabase', () => ({ supabase: {} }))
import { FundingWorkspace } from '../src/FundingWorkspace'
import { InvestorPage } from '../src/investors'
import { emptyOpportunity } from '../src/funding-model'
const session={user:{id:'admin'}}, staff={user_id:'admin',role:'platform_admin',active:true}
const row={...emptyOpportunity('existing'),opportunity:'Synthetic program',provider:'Example provider',official_url:'https://example.test/',version:1}
function backend({rows=[],loadError=null,write={data:{...row,id:'new',version:1},error:null}}={}) { const calls=[]; const chain={select:vi.fn(()=>chain),order:vi.fn(()=>chain),limit:vi.fn(()=>Promise.resolve({data:rows,error:loadError})),insert:vi.fn(p=>{calls.push(p);return chain}),update:vi.fn(p=>{calls.push(p);return chain}),eq:vi.fn(()=>chain),maybeSingle:vi.fn(()=>typeof write==='function'?write():Promise.resolve(write))};return {from:vi.fn(()=>chain),chain,calls} }
afterEach(cleanup)
async function addForm(client) { render(<FundingWorkspace session={session} staff={staff} client={client}/>); await waitFor(()=>expect(screen.getByRole('button',{name:'Add opportunity'}).disabled).toBe(false)); fireEvent.click(screen.getByRole('button',{name:'Add opportunity'})); fireEvent.change(screen.getByLabelText('Opportunity *'),{target:{value:'New lead'}});fireEvent.change(screen.getByLabelText('Provider *'),{target:{value:'Provider'}});fireEvent.change(screen.getByLabelText('Official HTTPS source *'),{target:{value:'https://example.test/'}}) }
describe('private tracker',()=>{
  it('does not query for signed out, tenant, inactive, mismatched or lower staff roles',()=>{for(const s of [null,{...staff,role:'support'},{...staff,active:false},{...staff,user_id:'other'}]){const client=backend();const view=render(<FundingWorkspace session={session} staff={s} client={client}/>);expect(client.from).not.toHaveBeenCalled();view.unmount()}})
  it('fails closed on missing setup and permits retry',async()=>{const client=backend({loadError:{message:'missing table'}});render(<FundingWorkspace session={session} staff={staff} client={client}/>);await screen.findByRole('alert');expect(screen.getByRole('button',{name:'Add opportunity'}).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Refresh'}));await waitFor(()=>expect(client.chain.limit).toHaveBeenCalledTimes(2))})
  it('saves once despite repeated submit and retains stable client id',async()=>{let resolve;const client=backend({write:()=>new Promise(r=>{resolve=r})});await addForm(client);const button=screen.getByRole('button',{name:'Save opportunity'});fireEvent.submit(button.closest('form'));fireEvent.submit(button.closest('form'));expect(client.calls.length).toBe(1);expect(client.calls[0].id).toBeTruthy();resolve({data:{...row,opportunity:'New lead'},error:null});await screen.findByText('Opportunity saved to the private CerbTek funding workspace.');expect(screen.queryByRole('button',{name:'Save opportunity'})).toBe(null)})
  it('retains draft on uncertain save without claiming success',async()=>{await addForm(backend({write:{error:{message:'network'}}}));fireEvent.click(screen.getByRole('button',{name:'Save opportunity'}));await screen.findByRole('alert');expect(screen.getByLabelText('Opportunity *').value).toBe('New lead');expect(screen.queryByText('Opportunity saved to the private CerbTek funding workspace.')).toBe(null)})
  it('guards edits with row version and retains conflicting draft',async()=>{const client=backend({rows:[row],write:{data:null,error:null}});render(<FundingWorkspace session={session} staff={staff} client={client}/>);fireEvent.click(await screen.findByRole('button',{name:'Review / edit'}));fireEvent.change(screen.getByLabelText('Opportunity *'),{target:{value:'Changed'}});fireEvent.click(screen.getByRole('button',{name:'Save opportunity'}));await screen.findByText(/This record changed/);expect(client.chain.eq).toHaveBeenCalledWith('version',1);expect(screen.getByLabelText('Opportunity *').value).toBe('Changed')})
  it('keeps or discards edits without writing on cancel',async()=>{const client=backend();await addForm(client);fireEvent.click(screen.getByRole('button',{name:'Cancel'}));fireEvent.click(screen.getByRole('button',{name:'Keep editing'}));expect(screen.getByLabelText('Opportunity *').value).toBe('New lead');fireEvent.click(screen.getByRole('button',{name:'Cancel'}));fireEvent.click(screen.getByRole('button',{name:'Discard changes'}));expect(screen.queryByLabelText('Opportunity *')).toBe(null);expect(client.calls).toHaveLength(0)})
  it('removes private records immediately after permission/session change',async()=>{const client=backend({rows:[row]});const view=render(<FundingWorkspace session={session} staff={staff} client={client}/>);await screen.findByText('Synthetic program');view.rerender(<FundingWorkspace session={{user:{id:'tenant'}}} staff={staff} client={client}/>);expect(screen.queryByText('Synthetic program')).toBe(null);expect(screen.getByRole('alert').textContent).toContain('Internal access only')})
  it('reports unsaved edits to navigation and clears them on unmount',async()=>{const client=backend({rows:[row]});const changed=vi.fn();const view=render(<FundingWorkspace session={session} staff={staff} client={client} onDirtyChange={changed}/>);fireEvent.click(await screen.findByRole('button',{name:'Review / edit'}));fireEvent.change(screen.getByLabelText('Opportunity *'),{target:{value:'Unsaved'}});expect(changed).toHaveBeenLastCalledWith(true);view.unmount();expect(changed).toHaveBeenLastCalledWith(false)});
  it('filters records and treats HTML as text',async()=>{const client=backend({rows:[{...row,opportunity:'<img src=x onerror=alert(1)>'}]});const view=render(<FundingWorkspace session={session} staff={staff} client={client}/>);await screen.findByText('<img src=x onerror=alert(1)>');expect(view.container.querySelector('img')).toBe(null);fireEvent.change(screen.getByRole('searchbox'),{target:{value:'missing'}});expect(screen.getByText('No matching opportunities')).toBeTruthy()})
})
describe('public investor page',()=>{it('has working contact and sign-in links but no investor form or private pipeline',()=>{const {container}=render(<InvestorPage/>);expect(screen.getByRole('heading',{level:1}).textContent).toContain('AI ambition');expect(container.querySelectorAll('a[href^="mailto:tim.gill@cerbtek.com"]').length).toBe(2);expect(container.querySelector('form')).toBe(null);expect(container.textContent).not.toContain('Cofounders');expect(container.textContent).not.toContain('Funding opportunities');expect(container.textContent).toContain('not an offer to sell securities')})})
