import React from 'react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { sectionFromHash, useSectionNavigation } from '../src/use-section-navigation'
import { ventureLabel, opportunityPayload, emptyOpportunity } from '../src/funding-model'

function Navigation({ guard }) {
  const [active, navigate] = useSectionNavigation(guard)
  return <><p data-testid="active">{active}</p><button onClick={() => navigate('Overview')}>Leave</button><button onClick={() => navigate('Funding')}>Funding</button></>
}
afterEach(() => { cleanup(); window.history.replaceState({}, '', '/'); vi.restoreAllMocks(); vi.unstubAllGlobals() })
describe('funding integration with current navigation', () => {
  it('recognizes the funding deep link and preserves existing section identifiers', () => {
    expect(sectionFromHash('#Funding')).toBe('Funding')
    expect(sectionFromHash('#CerbTek%20Staff')).toBe('CerbTek Staff')
    expect(sectionFromHash('#AI%20Ops')).toBe('AI Ops')
  })
  it('keeps a dirty funding workspace on navigation cancellation', () => {
    window.history.replaceState({}, '', '/#Funding')
    const guard=vi.fn(() => false)
    render(<Navigation guard={guard}/>)
    fireEvent.click(screen.getByText('Leave'))
    expect(screen.getByTestId('active').textContent).toBe('Funding')
    expect(window.location.hash).toBe('#Funding')
    expect(guard).toHaveBeenCalledWith('Overview', 'Funding')
  })
  it('guards browser back/forward state and restores the funding route on cancellation', () => {
    window.history.replaceState({}, '', '/?kairoCompany=tenant#Funding')
    render(<Navigation guard={() => false}/>)
    window.history.replaceState({}, '', '/app/?kairoCompany=tenant#Overview')
    fireEvent.popState(window)
    expect(screen.getByTestId('active').textContent).toBe('Funding')
    expect(window.location.hash).toBe('#Funding')
    expect(window.location.search).toBe('?kairoCompany=tenant')
  })
  it('moves after confirmation without prompting twice on the resulting hash event', async () => {
    window.history.replaceState({}, '', '/#Funding')
    const guard=vi.fn(() => true)
    render(<Navigation guard={guard}/>)
    fireEvent.click(screen.getByText('Leave'))
    await waitFor(() => expect(screen.getByTestId('active').textContent).toBe('Overview'))
    fireEvent(window, new HashChangeEvent('hashchange'))
    expect(guard).toHaveBeenCalledTimes(1)
  })
  it('preserves /app history after cancelling and later accepting actual Back and Forward', async () => {
    window.history.replaceState({ existing: 'keep' }, '', '/app/?kairoCompany=tenant#Overview')
    const guard=vi.fn(() => true)
    render(<Navigation guard={guard}/>)
    fireEvent.click(screen.getByText('Funding'))
    const length=window.history.length
    guard.mockReturnValue(false)
    await act(async () => { window.history.back(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(window.location.hash).toBe('#Funding'))
    expect(screen.getByTestId('active').textContent).toBe('Funding')
    expect(window.history.length).toBe(length)
    guard.mockReturnValue(true)
    await act(async () => { window.history.back(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(screen.getByTestId('active').textContent).toBe('Overview'))
    expect(window.location.search).toBe('?kairoCompany=tenant')
    expect(window.history.state.existing).toBe('keep')
    await act(async () => { window.history.forward(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(screen.getByTestId('active').textContent).toBe('Funding'))
  })
  it('preserves the forward entry when actual Forward is cancelled', async () => {
    window.history.replaceState({}, '', '/#Funding')
    const guard=vi.fn(() => true)
    render(<Navigation guard={guard}/>)
    fireEvent.click(screen.getByText('Leave'))
    await act(async () => { window.history.back(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(screen.getByTestId('active').textContent).toBe('Funding'))
    guard.mockReturnValue(false)
    await act(async () => { window.history.forward(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(window.location.hash).toBe('#Funding'))
    guard.mockReturnValue(true)
    await act(async () => { window.history.forward(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(screen.getByTestId('active').textContent).toBe('Overview'))
  })
  it('retains workflow history entries and other state during multi-entry Back cancellation', async () => {
    window.history.replaceState({ preserved: true }, '', '/?kairoWorkflow=first#Overview')
    const guard=vi.fn(() => true)
    render(<Navigation guard={guard}/>)
    window.history.pushState({ workflow: 'second' }, '', '/?kairoWorkflow=second#Overview')
    window.history.replaceState({ workflow: 'second', company: 'tenant' }, '', '/?kairoCompany=tenant&kairoWorkflow=second#Overview')
    fireEvent.click(screen.getByText('Funding'))
    guard.mockReturnValue(false)
    await act(async () => { window.history.go(-2); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(window.location.hash).toBe('#Funding'))
    expect(window.history.state.workflow).toBe('second')
    expect(window.location.search).toContain('kairoCompany=tenant')
    guard.mockReturnValue(true)
    await act(async () => { window.history.go(-2); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(window.location.search).toBe('?kairoWorkflow=first'))
    expect(window.history.state.preserved).toBe(true)
    await act(async () => { window.history.forward(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(window.history.state.workflow).toBe('second'))
    expect(window.history.state.company).toBe('tenant')
  })
  it('can cancel Back to an older unmarked entry when the browser exposes its position', async () => {
    window.history.replaceState({ older: true }, '', '/#Overview')
    window.history.pushState({}, '', '/#Funding')
    vi.stubGlobal('navigation', { get currentEntry() { return { index: window.location.hash === '#Funding' ? 1 : 0 } } })
    const guard=vi.fn(() => false)
    render(<Navigation guard={guard}/>)
    await act(async () => { window.history.back(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(window.location.hash).toBe('#Funding'))
    guard.mockReturnValue(true)
    await act(async () => { window.history.back(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(screen.getByTestId('active').textContent).toBe('Overview'))
    expect(window.history.state.older).toBe(true)
  })
  it('guards native hash links without deleting their forward entry', async () => {
    window.history.pushState({}, '', '/#Funding')
    const guard=vi.fn(() => false)
    render(<Navigation guard={guard}/>)
    await act(async () => { window.location.hash='#Overview'; await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(window.location.hash).toBe('#Funding'))
    guard.mockReturnValue(true)
    await act(async () => { window.history.forward(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(screen.getByTestId('active').textContent).toBe('Overview'))
  })
  it('preserves the draft and legacy entry when an older browser cannot locate the Back target', async () => {
    window.history.replaceState({ legacy: true }, '', '/#Overview')
    window.history.pushState({}, '', '/#Funding')
    const guard=vi.fn(() => false)
    render(<Navigation guard={guard}/>)
    const length=window.history.length
    await act(async () => { window.history.back(); await new Promise(resolve => setTimeout(resolve, 40)) })
    expect(screen.getByTestId('active').textContent).toBe('Funding')
    expect(window.location.hash).toBe('#Overview')
    expect(window.history.state).toEqual({ legacy: true })
    expect(window.history.length).toBe(length)
    expect(guard).toHaveBeenCalledTimes(1)
    await act(async () => { window.history.forward(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(window.location.hash).toBe('#Funding'))
    guard.mockReturnValue(true)
    await act(async () => { window.history.back(); await new Promise(resolve => setTimeout(resolve, 40)) })
    await waitFor(() => expect(screen.getByTestId('active').textContent).toBe('Overview'))
  })
  it('displays Kairo without changing the database venture contract', () => {
    const record=emptyOpportunity('example')
    expect(ventureLabel(record.venture)).toBe('Kairo')
    record.official_url='https://example.test/'
    expect(opportunityPayload(record).venture).toBe('CerbTek AI Enablement')
  })
})
