import { readFile, readdir } from 'node:fs/promises'
import assert from 'node:assert/strict'
import { JSDOM } from 'jsdom'
const base=process.env.EXPECTED_BASE || '/'
const out=new URL('../dist/',import.meta.url)
const root=await readFile(new URL('index.html',out),'utf8')
const product=await readFile(new URL('products/kairo/index.html',out),'utf8')
const doc=new JSDOM(product).window.document
assert.notEqual(product,root,'The company homepage and Kairo product entry must be distinct')
const company=new JSDOM(root).window.document
assert.equal(company.title,'CerbTek | Innovate. Secure. Dominate.')
assert.equal(company.querySelector('link[rel="canonical"]').href,'https://www.cerbtek.com/')
assert.equal(company.querySelector('meta[property="og:url"]').content,'https://www.cerbtek.com/')
assert.equal(company.querySelector('meta[property="og:image"]').content,'https://www.cerbtek.com/cerbtek-logo.png')
assert.equal(company.querySelector('link[rel="icon"]').getAttribute('href'),base+'cerbtek-logo.png?v=20261009-profile')
assert.equal(company.querySelectorAll('h1').length,1)
assert.equal(company.querySelector('h1').textContent,'INNOVATE. SECURE. DOMINATE.')
assert.doesNotMatch(company.body.textContent,/SOFTWARE DEVELOPMENT|Build what’s|Let’s talk|Kairo sign-in/)
assert.equal(company.querySelector('.page-art img').getAttribute('src'),base+'cerbtek-hero-strength-wide.webp')
assert.equal(company.querySelector('.page-art img').getAttribute('width'),'1672')
assert.equal(company.querySelector('.page-art img').getAttribute('height'),'941')
assert.equal(company.querySelector('.page-art img').getAttribute('fetchpriority'),'high')
assert.equal(company.querySelector('link[rel="shortcut icon"]').getAttribute('href'),base+'cerbtek-logo.png?v=20261009-profile')
assert.equal(company.querySelector('link[rel="apple-touch-icon"]').getAttribute('href'),base+'cerbtek-logo.png?v=20261009-profile')
const heroCss=await readFile(new URL('../src/company.css',import.meta.url),'utf8')
assert.equal(company.querySelector('.brand-tagline').textContent,'INNOVATE. SECURE. DOMINATE.')
assert.equal(company.querySelectorAll('.art-crop').length,0,'Use the standalone high-resolution artwork, never a magnified guide panel')
assert.doesNotMatch(heroCss,/386\.896552|241\.724138|131\.557377/,'Retire the tiny guide-panel crop')


assert.equal(company.querySelectorAll('.product-link').length,4)
assert.equal(company.querySelectorAll('.product-card,section').length,0,'Homepage remains a single artwork-led view')
assert.ok(company.body.textContent.trim().split(/\s+/).length<40,'Homepage copy stays minimal')
assert.equal(company.querySelector('.landing>.page-art').getAttribute('aria-hidden'),'true')
assert.match(heroCss,/min-height:100svh/,'Artwork-led page fills the viewport')
assert.match(heroCss,/object-fit:cover/,'Standalone artwork covers the full-page canvas without distortion')
assert.match(heroCss,/@media\(max-width:760px\)/,'Responsive mobile layout retained')
assert.equal(company.querySelector('.page-art source').getAttribute('srcset'),base+'cerbtek-hero-strength-portrait.webp','Portrait devices receive the approved close-up composition')
assert.ok(heroCss.includes('(max-width:1100px) and (max-aspect-ratio:4/3)'),'Portrait tablets receive the complete-profile composition')
assert.ok(heroCss.includes('padding-top:clamp(300px,72vw,760px)'),'Portrait copy scales below the featured artwork')
assert.equal(company.querySelectorAll('form').length,0)
assert.deepEqual([...company.querySelectorAll('.product-link')].map(a=>a.getAttribute('href')),[base+'products/kairo','https://www.forgecif.com/','https://www.lorerise.com/','https://treestand-manager.webflow.io/'])
for(const brand of company.querySelectorAll('a.company-brand')) assert.equal(brand.getAttribute('href'),base)
for(const link of company.querySelectorAll('a[href^="#"]')) assert.ok(company.getElementById(link.hash.slice(1)),link.hash)
assert.equal(company.querySelectorAll('.footer-bottom a').length,1)
assert.doesNotMatch(root,/kairo-banner|kairo-touch-icon|Put AI to work|monthly or annual billing/)
assert.equal(doc.querySelector('link[rel="canonical"]').href,'https://www.cerbtek.com/products/kairo')
assert.equal(doc.querySelector('meta[property="og:url"]').content,'https://www.cerbtek.com/products/kairo')
assert.equal(doc.querySelector('meta[property="og:image"]').content,'https://www.cerbtek.com/kairo-banner.png')
assert.ok(doc.title.startsWith('Kairo by CerbTEK |'))
for(const link of doc.querySelectorAll('a.wordmark')) assert.equal(link.getAttribute('href'),base+'products/kairo')
assert.equal(doc.querySelector('[aria-current="page"]').getAttribute('href'),base+'products/kairo')
assert.doesNotMatch(product,/href="https:\/\/kairo\.cerbtek\.com/,'Unconfigured customer subdomain must not receive traffic')
assert.equal(doc.querySelectorAll('h1').length,1)
assert.ok(doc.title.includes('Put AI to work'))
assert.ok(doc.querySelector('meta[name="description"]').content.length>70)
assert.doesNotMatch(root, /tim\.gill@cerbtek\.com|contact Tim Gill/)
assert.equal(doc.querySelectorAll('form').length,0,'No unconnected forms or fake lead storage')
for(const link of doc.querySelectorAll('a[href^="#"]')) assert.ok(doc.getElementById(link.hash.slice(1)),link.hash)
for(const link of doc.querySelectorAll('a[href^="mailto:"]')) assert.equal(new URL(link.href).pathname,'info@cerbtek.com')
assert.ok([...doc.querySelectorAll('a')].some(a=>a.getAttribute('href')===base+'app/kairo'))
assert.ok([...doc.querySelectorAll('a')].some(a=>a.getAttribute('href')===base+'investors/'))
assert.ok(!root.includes('%BASE_URL%'))
const seen=new Set()
async function checkModule(path){
 if(seen.has(path))return;seen.add(path)
 const source=await readFile(new URL('assets/'+path.split('/').at(-1),out),'utf8')
 assert.doesNotMatch(source,/supabase|suohuogalotxhsnkumvy|sb_publishable|cerbtek_funding_opportunities|staff_accounts|Cofounders Capital|Veteran Fund|NSF 26-510/)
 for(const m of source.matchAll(/(?:from\s*|import\s*)["'](\.\/[^"']+\.js)["']/g))await checkModule(m[1])
}
for(const publicDoc of [company,doc]) for(const script of publicDoc.querySelectorAll('script[src],link[rel="modulepreload"]')) await checkModule(script.getAttribute('src')||script.getAttribute('href'))
const app=await readFile(new URL('app/kairo/index.html',out),'utf8')
const legacyApp=await readFile(new URL('app/index.html',out),'utf8')
assert.equal(legacyApp,app,'Both app entries run the same exact-route gate')
assert.match(app,/Kairo by CerbTEK \| Client sign-in/);assert.match(app,/name="robots" content="noindex"/)
const investor=await readFile(new URL('investors/index.html',out),'utf8')
assert.match(investor,/Investors/)
const investorSource=await readFile(new URL('../src/investors.jsx',import.meta.url),'utf8')
assert.doesNotMatch(investorSource,/tim\.gill@cerbtek\.com|contact Tim Gill/)
assert.equal([...investorSource.matchAll(/mailto:([^?"]+)/g)].length,2)
for(const match of investorSource.matchAll(/mailto:([^?"]+)/g)) assert.equal(match[1],'info@cerbtek.com')
for(const publicDoc of [company,doc]) for(const img of publicDoc.querySelectorAll('img')){const src=img.getAttribute('src');assert.ok(src.startsWith(base));await readFile(new URL(src.slice(base.length),out))}
assert.match(product,/monthly or annual billing/);assert.match(product,/separate implementation fee/);assert.doesNotMatch(product,/local prototype|live phone service|IN DEVELOPMENT|in development|honest roadmap|role-specific|AI-ASSISTED WORK/);assert.match(product,/INSIDE KAIRO/)
for(const page of [root,product,app,investor]) assert.doesNotMatch(page,/%KAIRO_BASE%/,'All entry assets use the resolved mount')
assert.equal(new JSDOM(investor).window.document.querySelector('link[rel="canonical"]').href,'https://www.cerbtek.com/investors')
console.log('PASS distinct CerbTEK company and Kairo product routes, canonical metadata, brand and mount-aware navigation; marketing metadata, real email CTA, assets, navigation and backend-free public dependency graph; app and investors retained at '+base)
