import test from 'node:test';import assert from 'node:assert/strict';
import {createHandler} from '../candidate/edge/agent-run/handler.ts';
globalThis.fetch=async()=>{throw new Error('Network forbidden; mocks only')};
const copy=x=>structuredClone(x);
function fixture(){return{user:'human2',events:[],calls:[],fail:{},runs:[],tables:{ai_agents:[{id:'agent',organization_id:'org'}],oauth_connections:[{id:'connection',integration_id:'integration',organization_id:'org',provider:'microsoft',status:'Connected',oauth_verified_version:1,external_account_id:'account',scopes:['Mail.Send','User.Read']}],integrations:[{id:'integration',organization_id:'org',provider:'Microsoft',integration_type:'OAuth',status:'Connected'}],action_requests:[]},steps:[{type:'note',text:'Known existing step'}],snapshot:{version:1,agent:{id:'agent'},workflow:{id:'workflow'},workflow_mapping:{execution_mode:'Execute'},policy:{required_roles:['admin']},integration_bindings:[],context:{}}}}
function deps(s){return{supabaseUrl:'https://local.test',now:()=>Date.parse('2026-10-08T12:00:00Z'),fetchImpl:async(url,options)=>{s.calls.push({url,options});return new Response(JSON.stringify({ok:true,result:{},summary:'Synthetic read'}),{status:200})},supabase:{auth:{getUser:async()=>({data:{user:{id:s.user,is_anonymous:s.anonymous}},error:s.authError?{}:null})},from(table){let filters=[],value,op='select';const q={select(){return q},eq(k,v){filters.push([k,v]);return q},insert(v){value=v;op='insert';return q},update(v){value=v;op='update';return q},async run(){s.events.push([table,op]);if(s.fail[table])return{error:{},data:null};const rows=table==='workflow_runs'?s.runs:(s.tables[table]||[]);let found=rows.filter(r=>filters.every(([k,v])=>r[k]===v));if(op==='insert'){const row={id:'action',...value};rows.push(row);found=[row]}if(op==='update')for(const row of found)Object.assign(row,copy(value));return{data:found.length===1?copy(found[0]):null,error:found.length!==1?{}:null}},single(){return q.run()},then(a,b){return q.run().then(a,b)}};return q},async rpc(name,args){s.events.push(['rpc',name,copy(args)]);if(s.fail[name])return{data:null,error:{}};
 if(s.overrides?.[name])return copy(s.overrides[name]);
 if(name==='create_agent_workflow_request')return{data:{id:'proposal',status:'Pending',organization_id:'org',agent_id:'agent',workflow_id:'workflow',requested_by:s.user,approved_by:null,workflow_run_id:null,execution_snapshot:s.snapshot},error:null};
 if(name==='review_agent_workflow_request')return{data:{id:args.p_request_id,status:args.p_approve?'Approved':'Rejected',approved_by:args.p_approve?s.user:null,requested_by:'human1'},error:null};
 if(name==='reserve_agent_workflow'){if(s.runs.length)return{data:null,error:{}};const run={id:'run',organization_id:'org',workflow_id:'workflow',agent_run_request_id:args.p_request_id,status:'Running',current_step:0,initiated_by:'human1',workflow_revision:'revision',workflow_steps:copy(s.steps),workflow_context:{},context:{}};s.runs.push(run);return{data:copy(run),error:null}}
 if(name==='assert_agent_workflow_lineage')return{data:{agent_request_id:'proposal',run_id:'run',snapshot:s.snapshot},error:null};
 if(name==='finish_agent_workflow')return{data:true,error:null};
 throw new Error('Unexpected RPC '+name)
}}}}
async function invoke(s,body,headers={Authorization:'Bearer synthetic'}){const r=await createHandler(deps(s))(new Request('https://local.test',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)}));return{status:r.status,body:await r.json()}}
const propose={op:'request',organization_id:'org',agent_id:'agent',workflow_id:'workflow',context:{}};
for(const extra of [{confidence:100},{autonomous:true},{approved_by:'human2'},{status:'Approved'},{workflow_run_id:'forged'},{execution_snapshot:{}}])test(`client authority fields rejected ${JSON.stringify(extra)}`,async()=>{const s=fixture();const r=await invoke(s,{...propose,...extra});assert.equal(r.status,400);assert.equal(s.events.length,0)});
test('new request is Pending and never dispatches even snapshot mentions Execute',async()=>{const s=fixture();const r=await invoke(s,propose);assert.equal(r.status,200);assert.equal(r.body.status,'Pending');assert.equal(r.body.workflow_status,null);assert.equal(s.calls.length,0);assert.equal(s.runs.length,0)});
for(const context of [{agent_id:'forged'},{deep:[[{outputs:[]}]]},{approved_by:'forged'}])test(`reject nested forged context ${JSON.stringify(context)}`,async()=>{const s=fixture();const r=await invoke(s,{...propose,context});assert.equal(r.status,400);assert.equal(s.runs.length,0)});
test('UI-selected tenant mismatch denies before proposal creation',async()=>{const s=fixture();const r=await invoke(s,{...propose,organization_id:'foreign'});assert.equal(r.status,403);assert(!s.events.some(e=>e[1]==='create_agent_workflow_request'))});
for(const op of ['approve','reject'])test(`explicit ${op} uses server review RPC with authenticated human`,async()=>{const s=fixture();const r=await invoke(s,{op,request_id:'proposal'});assert.equal(r.status,200);assert.equal(r.body.status,op==='approve'?'Approved':'Rejected');assert.equal(s.events[0][2].p_actor_id,'human2');assert.equal(s.calls.length,0)});
test('self approval result fails defense in depth',async()=>{const s=fixture();s.overrides={review_agent_workflow_request:{data:{id:'proposal',status:'Approved',approved_by:'human2',requested_by:'human2'},error:null}};assert.equal((await invoke(s,{op:'approve',request_id:'proposal'})).status,409)});
test('note workflow returns Executed only after acknowledged finish',async()=>{const s=fixture();const r=await invoke(s,{op:'execute',request_id:'proposal'});assert.equal(r.status,200);assert.equal(r.body.status,'Executed');assert.equal(r.body.workflow_status,'Success');assert.equal(s.runs[0].status,'Success');assert.equal(s.events.at(-1)[1],'finish_agent_workflow')});
test('queued email remains Approved + Waiting Approval, never finalizes',async()=>{const s=fixture();s.steps=[{type:'approval.email',to:'synthetic@example.invalid',subject:'Subject',message:'Body'}];const r=await invoke(s,{op:'execute',request_id:'proposal'});assert.equal(r.status,200);assert.equal(r.body.status,'Approved');assert.equal(r.body.workflow_status,'Waiting Approval');assert.equal(s.tables.action_requests[0].status,'Pending');assert.equal(s.tables.action_requests[0].requested_by,'human1');assert(!s.events.some(e=>e[1]==='finish_agent_workflow'));assert.equal(s.calls.length,0)});
test('terminal bookkeeping failure is 202 nonretryable and preserves Success',async()=>{const s=fixture();s.fail.finish_agent_workflow=true;const r=await invoke(s,{op:'execute',request_id:'proposal'});assert.equal(r.status,202);assert.equal(r.body.ok,false);assert.equal(r.body.status,'Approved');assert.equal(r.body.workflow_status,'Reconciliation required');assert.equal(r.body.retryable,false);assert.equal(s.runs[0].status,'Success')});
test('lost lineage never falls back to manual or reaches provider',async()=>{const s=fixture();s.overrides={assert_agent_workflow_lineage:{data:null,error:null}};s.steps=[{type:'microsoft.profile'}];const r=await invoke(s,{op:'execute',request_id:'proposal'});assert.equal(r.status,409);assert.equal(s.calls.length,0);assert.equal(s.runs[0].status,'Error')});
test('repeat execute cannot create a second linked workflow',async()=>{const s=fixture();await invoke(s,{op:'execute',request_id:'proposal'});const r=await invoke(s,{op:'execute',request_id:'proposal'});assert.equal(r.status,409);assert.equal(s.runs.length,1)});
for(const name of ['create_agent_workflow_request','review_agent_workflow_request','reserve_agent_workflow'])test(`${name} unacknowledged RPC result fails closed`,async()=>{const s=fixture();s.fail[name]=true;const body=name.startsWith('create')?propose:{op:name.startsWith('review')?'approve':'execute',request_id:'proposal'};assert.equal((await invoke(s,body)).status,409);assert.equal(s.calls.length,0)});
test('anonymous and missing sessions cannot issue agent authority',async()=>{for(const anonymous of [true,false]){const s=fixture();s.anonymous=anonymous;const r=await invoke(s,propose,anonymous?{Authorization:'Bearer fake'}:{});assert.equal(r.status,401);assert.equal(s.events.length,0)}});
