import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {createHandler as connectHandler} from '../candidate/edge/microsoft-connect/handler.ts';
import {createHandler as callbackHandler} from '../candidate/edge/microsoft-oauth-callback/handler.ts';
import {createHandler as executeHandler} from '../candidate/edge/microsoft-execute/handler.ts';
import {connectionBinding,getMicrosoftAccessToken,parseGrantedScopes} from '../candidate/edge/_shared/microsoft-connection.ts';
const id='11111111-1111-4111-8111-111111111111',org='22222222-2222-4222-8222-222222222222',actor='33333333-3333-4333-8333-333333333333',integrationId='44444444-4444-4444-8444-444444444444',stateId='55555555-5555-4555-8555-555555555555';
const url='https://synthetic.example';
const scopes=['Mail.Send','User.Read','offline_access','openid','profile'];
const base={id,organization_id:org,integration_id:integrationId,provider:'microsoft',tenant_id:'organizations',client_id:actor,client_secret_id:actor,access_secret_id:id,refresh_secret_id:org,status:'Connected',oauth_verified_version:1,oauth_revision:id,oauth_refresh_revision:stateId,scopes,external_account_id:'synthetic-account',token_expires_at:new Date(Date.now()-1000).toISOString()};
const integration={id:integrationId,organization_id:org,provider:'Microsoft',integration_type:'OAuth',status:'Connected',scopes:scopes.join(' '),oauth_revision:stateId};
const setup={state:stateId,connection_id:id,organization_id:org,tenant_id:'organizations',client_id:actor,client_secret_id:actor,scopes,code_verifier:'v'.repeat(64),redirect_uri:url+'/functions/v1/microsoft-oauth-callback'};
const token={access_token:'SYNTHETIC_ACCESS',refresh_token:'SYNTHETIC_REFRESH',expires_in:3600,token_type:'Bearer',scope:scopes.join(' ')};
const account={id:'synthetic-account',displayName:'Synthetic Account',userPrincipalName:'synthetic@example.invalid'};
function client({rpcOverride,tableOverride,authError=false}={}){
 const calls=[],writes=[];
 const defaults={begin_microsoft_oauth_setup:setup,claim_microsoft_oauth_setup:setup,edge_read_secret:'SYNTHETIC_CREDENTIAL',complete_microsoft_oauth_setup:true,fail_microsoft_oauth_setup:true,validate_microsoft_connection:true,commit_microsoft_refresh:true};
 const c={calls,writes,auth:{getUser:async()=>({data:{user:authError?null:{id:actor}},error:authError?{}:null})},
 rpc:async(name,args)=>{calls.push({name,args});const r=rpcOverride?.(name,args,calls);return r!==undefined?r:{data:defaults[name],error:null}},
 from(table){let mutation=null,filters=[];const q={select(){return q},eq(k,v){filters.push([k,v]);return q},insert(v){mutation={operation:'insert',value:v};return q},update(v){mutation={operation:'update',value:v};return q},single(){return q},maybeSingle(){return q},then(resolve,reject){if(mutation)writes.push({table,...mutation,filters});let r=tableOverride?.(table,mutation,filters);if(r===undefined)r={data:table==='integrations'?integration:table==='oauth_connections'?base:table==='organization_members'?{role:'owner'}:table==='staff_accounts'?null:null,error:null};return Promise.resolve(r).then(resolve,reject)}};return q}};
 return c;
}
const req=(body={organization_id:org,action:'health'},headers={Authorization:'Bearer synthetic-jwt'})=>new Request(url,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)});
function provider(responses=[token,account]){const calls=[];let position=0;return{calls,fetch:async(u,init)=>{calls.push({url:String(u),init});const r=responses[position++];if(r instanceof Error)throw r;return r instanceof Response?r:new Response(JSON.stringify(r??{}),{status:200,headers:{'Content-Type':'application/json'}})}}}
const tests=[];async function test(name,run){try{await run();tests.push({name,passed:true});console.log('PASS '+name)}catch(e){tests.push({name,passed:false,error:e.message});console.error('FAIL '+name+' '+e.stack)}}
const setupRequest={organization_id:org,client_id:actor,client_secret:'SYNTHETIC_CLIENT',scopes};
await test('connect uses authenticated actor and PKCE frozen setup URL',async()=>{const c=client();const r=await connectHandler({supabase:c,supabaseUrl:url})(req({...setupRequest,actor_id:'attacker'}));assert.equal(r.status,200);const j=await r.json();const a=new URL(j.authorize_url);assert.equal(a.searchParams.get('state'),stateId);assert.equal(a.searchParams.get('code_challenge_method'),'S256');assert.equal(c.calls[0].args.p_actor_id,actor);assert.equal(c.writes.length,0);assert.equal(a.searchParams.get('scope'),scopes.join(' '))});
await test('connect refuses unauthenticated caller',async()=>{const c=client({authError:true});assert.equal((await connectHandler({supabase:c,supabaseUrl:url})(req(setupRequest))).status,401);assert.equal(c.calls.length,0)});
await test('connect rejects unsupported scope without provider or storage',async()=>{const c=client();assert.equal((await connectHandler({supabase:c,supabaseUrl:url})(req({...setupRequest,scopes:[...scopes,'Directory.Read.All']}))).status,400);assert.equal(c.calls.length,0)});
await test('connect returns failure when atomic begin fails',async()=>{const c=client({rpcOverride:n=>n==='begin_microsoft_oauth_setup'?{data:null,error:{message:'private details'}}:undefined});const r=await connectHandler({supabase:c,supabaseUrl:url})(req(setupRequest));assert.equal(r.status,409);assert.ok(!(await r.text()).includes('private details'))});
await test('connect handles malformed JSON',async()=>{const c=client();assert.equal((await connectHandler({supabase:c,supabaseUrl:url})(new Request(url,{method:'POST',headers:{Authorization:'Bearer test'},body:'{'}))).status,400)});
await test('callback token exchange uses frozen state credentials and verifies mailbox first',async()=>{const c=client(),p=provider();const r=await callbackHandler({supabase:c,supabaseUrl:url,fetchImpl:p.fetch})(new Request(url+'?state='+stateId+'&code=synthetic-code'));assert.match(r.headers.get('location'),/microsoft=connected$/);assert.equal(p.calls.length,2);assert.match(p.calls[1].url,/graph.microsoft.com.*\/me/);assert.equal(c.calls.find(x=>x.name==='edge_read_secret').args.secret_id,setup.client_secret_id);assert.equal(c.calls.find(x=>x.name==='complete_microsoft_oauth_setup').args.p_account_id,account.id);assert.equal(c.writes.length,0)});
await test('callback denial consumes state without reading credentials',async()=>{const c=client(),p=provider();const r=await callbackHandler({supabase:c,supabaseUrl:url,fetchImpl:p.fetch})(new Request(url+'?state='+stateId+'&error=access_denied'));assert.match(r.headers.get('location'),/microsoft=error/);assert.deepEqual(c.calls.map(x=>x.name),['claim_microsoft_oauth_setup','fail_microsoft_oauth_setup']);assert.equal(p.calls.length,0)});
await test('callback rejected state makes no provider call',async()=>{const c=client({rpcOverride:n=>n==='claim_microsoft_oauth_setup'?{data:null,error:{}}:undefined}),p=provider();await callbackHandler({supabase:c,supabaseUrl:url,fetchImpl:p.fetch})(new Request(url+'?state='+stateId+'&code=code'));assert.equal(p.calls.length,0);assert.equal(c.calls.length,1)});
for(const [name,responses] of [
 ['failed Graph',[token,new Response('{}',{status:503})]],['missing identity',[token,{displayName:'No ID',mail:'x@y.invalid'}]],
 ['missing principal',[token,{id:'synthetic-account'}]],['token malformed',[{...token,access_token:undefined},account]],
 ['missing refresh',[{...token,refresh_token:undefined},account]],['missing scope',[{...token,scope:undefined},account]],
 ['scope expansion',[{...token,scope:token.scope+' Directory.Read.All'},account]],['token timeout',[new Error('network')]],
 ['provider non-JSON',[new Response('invalid-json',{status:200})]],['missing expires',[{...token,expires_in:undefined},account]],
])await test('callback '+name+' cannot mark Connected',async()=>{const c=client(),p=provider(responses);const r=await callbackHandler({supabase:c,supabaseUrl:url,fetchImpl:p.fetch})(new Request(url+'?state='+stateId+'&code=code'));assert.match(r.headers.get('location'),/microsoft=error/);assert.ok(!c.calls.some(x=>x.name==='complete_microsoft_oauth_setup'));assert.ok(c.calls.some(x=>x.name==='fail_microsoft_oauth_setup'))});
await test('callback completion false is a failure',async()=>{const c=client({rpcOverride:n=>n==='complete_microsoft_oauth_setup'?{data:false,error:null}:undefined}),p=provider();const r=await callbackHandler({supabase:c,supabaseUrl:url,fetchImpl:p.fetch})(new Request(url+'?state='+stateId+'&code=code'));assert.match(r.headers.get('location'),/microsoft=error/)});
await test('callback public redirect does not expose raw provider failure',async()=>{const c=client(),p=provider([new Response(JSON.stringify({error_description:'SYNTHETIC_SECRET_DO_NOT_LEAK'}),{status:400})]);const r=await callbackHandler({supabase:c,supabaseUrl:url,fetchImpl:p.fetch})(new Request(url+'?state='+stateId+'&code=code'));assert.ok(!r.headers.get('location').includes('SYNTHETIC_SECRET_DO_NOT_LEAK'))});
await test('refresh verifies same mailbox then commits exact CAS and binding',async()=>{const c=client(),p=provider();assert.equal(await getMicrosoftAccessToken({supabase:c,connection:base,fetchImpl:p.fetch}),'SYNTHETIC_ACCESS');const committed=c.calls.find(x=>x.name==='commit_microsoft_refresh');assert.equal(committed.args.expected_refresh_revision,base.oauth_refresh_revision);assert.deepEqual(committed.args.expected_binding,connectionBinding(base,integration));assert.equal(committed.args.verified_account_id,base.external_account_id);assert.equal(c.writes.length,0)});
await test('fresh access token requires live authority checks and no refresh',async()=>{const c=client(),p=provider();assert.equal(await getMicrosoftAccessToken({supabase:c,connection:{...base,token_expires_at:new Date(Date.now()+3600000).toISOString()},fetchImpl:p.fetch}),'SYNTHETIC_CREDENTIAL');assert.equal(p.calls.length,0);assert.equal(c.calls.filter(x=>x.name==='validate_microsoft_connection').length,2)});
await test('refresh mailbox substitution cannot reach commit',async()=>{const c=client(),p=provider([token,{...account,id:'other-account'}]);await assert.rejects(getMicrosoftAccessToken({supabase:c,connection:base,fetchImpl:p.fetch}),/identity/);assert.ok(!c.calls.some(x=>x.name==='commit_microsoft_refresh'))});
await test('refresh CAS rejection never releases uncommitted token',async()=>{const c=client({rpcOverride:n=>n==='commit_microsoft_refresh'?{data:null,error:{}}:undefined}),p=provider();await assert.rejects(getMicrosoftAccessToken({supabase:c,connection:base,fetchImpl:p.fetch}),/failed/);assert.equal(c.writes.length,0)});
await test('refresh CAS false never releases uncommitted token',async()=>{const c=client({rpcOverride:n=>n==='commit_microsoft_refresh'?{data:false,error:null}:undefined}),p=provider();await assert.rejects(getMicrosoftAccessToken({supabase:c,connection:base,fetchImpl:p.fetch}),/not committed/)});
await test('disabled connection stops before reading secrets or provider',async()=>{const c=client(),p=provider();await assert.rejects(getMicrosoftAccessToken({supabase:c,connection:{...base,status:'Disabled'},fetchImpl:p.fetch}),/unavailable/);assert.equal(c.calls.length,0);assert.equal(p.calls.length,0)});
await test('cross-tenant integration response cannot match context',async()=>{const c=client({tableOverride:t=>t==='integrations'?{data:{...integration,organization_id:'foreign'},error:null}:undefined}),p=provider();await assert.rejects(getMicrosoftAccessToken({supabase:c,connection:base,fetchImpl:p.fetch}));});
await test('integration scope mismatch stops secret reads',async()=>{const c=client({tableOverride:t=>t==='integrations'?{data:{...integration,scopes:'User.Read'},error:null}:undefined}),p=provider();await assert.rejects(getMicrosoftAccessToken({supabase:c,connection:base,fetchImpl:p.fetch}),/unavailable/);assert.equal(c.calls.length,0)});
await test('provider granted scope prefixes normalize without adding authority',async()=>{assert.deepEqual(parseGrantedScopes('https://graph.microsoft.com/User.Read openid profile email',['User.Read','openid','profile']),['User.Read','email','openid','profile'])});
await test('binding scopes are canonical and excludes token/health churn',async()=>{const b=connectionBinding(base,integration);assert.deepEqual(connectionBinding({...base,scopes:[...scopes].reverse().concat('User.Read'),token_expires_at:'tomorrow',oauth_refresh_revision:'next'},{...integration,notes:'changed'}),b)});
await test('execute valid health never writes Connected status',async()=>{const c=client(),p=provider([account]);const r=await executeHandler({supabase:c,fetchImpl:p.fetch,getAccessToken:async()=> 'SYNTHETIC_ACCESS'})(req());assert.equal(r.status,200);assert.ok(c.writes.every(w=>w.table!=='oauth_connections'));assert.ok(c.writes.filter(w=>w.table==='integrations').every(w=>!('status'in w.value)))});
await test('execute provider failure cannot mark or restore Connected',async()=>{const c=client(),p=provider([new Error('SYNTHETIC_PROVIDER_SECRET')]);const r=await executeHandler({supabase:c,fetchImpl:p.fetch,getAccessToken:async()=> 'SYNTHETIC_ACCESS'})(req());assert.equal(r.status,502);assert.ok(c.writes.every(w=>!['oauth_connections','integrations'].includes(w.table)));assert.ok(!(await r.text()).includes('SYNTHETIC_PROVIDER_SECRET'))});
await test('execute missing action scope makes no token or provider call',async()=>{let tokens=0;const c=client(),p=provider();const r=await executeHandler({supabase:c,fetchImpl:p.fetch,getAccessToken:async()=>{tokens++;return 'SYNTHETIC_ACCESS'}})(req({organization_id:org,action:'inbox-status'}));assert.equal(r.status,403);assert.equal(tokens,0);assert.equal(p.calls.length,0)});
await test('execute cannot introduce write action',async()=>{const c=client(),p=provider();const r=await executeHandler({supabase:c,fetchImpl:p.fetch})(req({organization_id:org,action:'send-email'}));assert.equal(r.status,400);assert.equal(p.calls.length,0)});
const runId='66666666-6666-4666-8666-666666666666', requestId='77777777-7777-4777-8777-777777777777';
const workflowRun={id:runId,organization_id:org,workflow_id:stateId,status:'Running',current_step:0,workflow_steps:[{type:'microsoft.health'}],workflow_revision:'2026-10-08T00:00:00Z',agent_run_request_id:requestId};
const definition={id:stateId,organization_id:org,status:'Active',steps:workflowRun.workflow_steps,updated_at:workflowRun.workflow_revision};
function workflowClient({run=workflowRun,lineage={agent_request_id:requestId},definitionRow=definition}={}){return client({tableOverride:t=>t==='workflow_runs'?{data:run,error:null}:t==='workflow_definitions'?{data:definitionRow,error:null}:undefined,rpcOverride:n=>n==='assert_agent_workflow_lineage'?{data:lineage,error:null}:undefined})}
await test('execute approved workflow checks exact lineage twice',async()=>{const c=workflowClient(),p=provider([account]);const r=await executeHandler({supabase:c,fetchImpl:p.fetch,getAccessToken:async()=> 'SYNTHETIC_ACCESS'})(req({organization_id:org,action:'health',workflow_run_id:runId}));assert.equal(r.status,200);assert.equal(c.calls.filter(x=>x.name==='assert_agent_workflow_lineage').length,2)});
await test('execute linked agent run cannot downgrade null lineage to manual',async()=>{let tokens=0;const c=workflowClient({lineage:null}),p=provider();const r=await executeHandler({supabase:c,fetchImpl:p.fetch,getAccessToken:async()=>{tokens++;return 'SYNTHETIC_ACCESS'}})(req({organization_id:org,action:'health',workflow_run_id:runId}));assert.equal(r.status,502);assert.equal(tokens,0);assert.equal(p.calls.length,0)});
await test('execute manual run rejects unexpected agent assertion',async()=>{let tokens=0;const c=workflowClient({run:{...workflowRun,agent_run_request_id:null}}),p=provider();const r=await executeHandler({supabase:c,fetchImpl:p.fetch,getAccessToken:async()=>{tokens++;return 'SYNTHETIC_ACCESS'}})(req({organization_id:org,action:'health',workflow_run_id:runId}));assert.equal(r.status,502);assert.equal(tokens,0)});
await test('execute rejects workflow action substitution before credentials',async()=>{let tokens=0;const c=workflowClient({run:{...workflowRun,workflow_steps:[{type:'note'}]}}),p=provider();const r=await executeHandler({supabase:c,fetchImpl:p.fetch,getAccessToken:async()=>{tokens++;return 'SYNTHETIC_ACCESS'}})(req({organization_id:org,action:'health',workflow_run_id:runId}));assert.equal(r.status,502);assert.equal(tokens,0);assert.equal(p.calls.length,0)});
await test('execute rejects changed workflow revision before credentials',async()=>{let tokens=0;const c=workflowClient({definitionRow:{...definition,updated_at:'changed'}}),p=provider();const r=await executeHandler({supabase:c,fetchImpl:p.fetch,getAccessToken:async()=>{tokens++;return 'SYNTHETIC_ACCESS'}})(req({organization_id:org,action:'health',workflow_run_id:runId}));assert.equal(r.status,502);assert.equal(tokens,0)});
await test('execute late agent revocation stops Graph after token lookup',async()=>{const c=workflowClient(),original=c.rpc;let checks=0;c.rpc=async(n,args)=>n==='assert_agent_workflow_lineage'&&++checks>1?{data:null,error:{}}:original(n,args);const p=provider([account]);let tokens=0;const r=await executeHandler({supabase:c,fetchImpl:p.fetch,getAccessToken:async()=>{tokens++;return 'SYNTHETIC_ACCESS'}})(req({organization_id:org,action:'health',workflow_run_id:runId}));assert.equal(r.status,502);assert.equal(tokens,1);assert.equal(p.calls.length,0)});
await test('execute rejects caller-supplied agent lineage fields',async()=>{const c=client(),p=provider();const r=await executeHandler({supabase:c,fetchImpl:p.fetch})(req({organization_id:org,action:'health',agent_run_request_id:requestId}));assert.equal(r.status,400);assert.equal(c.calls.length,0);assert.equal(p.calls.length,0)});
const report={mode:'Offline actual TypeScript handlers and helper, mocked Supabase and provider; no real tokens or provider calls',passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length,tests};await writeFile(new URL('../evidence/oauth-route-results.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed}));if(report.failed)process.exitCode=1;
