import React from 'react'
import { customerRequestEvidence, reportingNumber, reportingReservation } from './customer-reporting-model'
import { formatTime, validKnowledgeSources } from './customer-reply-model'
import { formatElapsed } from './workflow-monitor-data'
import './customer-reporting.css'

function Fact({ label, children }) { return <div><dt>{label}</dt><dd>{children}</dd></div> }
export function CustomerUsageSummary({ report }) {
  return <section className="cor-usage" aria-label="Recorded customer AI usage"><h3>Recorded customer AI usage</h3><dl className="cor-facts"><Fact label="Linked AI requests">{report.usage.runs}</Fact><Fact label="Input tokens">{reportingNumber(report.usage.input.value)}</Fact><Fact label="Output tokens">{reportingNumber(report.usage.output.value)}</Fact><Fact label="Measured spend">Not recorded</Fact></dl><p className="cor-muted">Input usage recorded for {report.usage.input.recorded} of {report.usage.runs} linked AI requests; output usage for {report.usage.output.recorded} of {report.usage.runs}. Missing usage is not zero. These are the current bound attempts in the loaded request sample, not all account usage.</p>
    {report.models.length > 0 && <details><summary>Models and reserved allowances</summary><div className="cor-models">{report.models.map((model, index) => <div key={index}><h4>{model.provider || 'Provider not recorded'} / {model.model || 'Model not recorded'}</h4><p>{model.runs} linked AI requests · input {reportingNumber(model.input.value)} · output {reportingNumber(model.output.value)}</p><p>Saved reservation allowances: {reportingReservation(model.reservation.value)} ({model.reservation.recorded} of {model.runs} recorded)</p></div>)}</div><p className="cor-muted">Reservations are admission-control allowances, not actual spend, invoice charges, or a remaining balance. No price estimate is calculated.</p></details>}
  </section>
}
export default function CustomerRequestEvidence({ workflow }) {
  const evidence = customerRequestEvidence(workflow), { run, action, receipt, usage } = evidence
  const knowledgeUnavailable = workflow.knowledge_stale || !validKnowledgeSources(workflow.knowledge_sources || [])
  return <section className="cor-evidence" aria-label="Request history and usage">
    <h3>Request history and usage</h3>
    <div className="cor-outcome"><h4>{evidence.email.label}</h4><p>{evidence.email.detail}</p><dl className="cor-facts"><Fact label="Email delivery">{evidence.delivery}</Fact><Fact label="Business resolution">{evidence.resolution}</Fact></dl></div>
    <dl className="cor-facts"><Fact label="Saved request revision">{workflow.revision}</Fact><Fact label="Bound AI request">{run?.id || (workflow.ai_request_key ? 'Prepared key; no verified run' : 'None linked')}</Fact><Fact label="Saved provider / model">{usage.provider && usage.model ? `${usage.provider} / ${usage.model}` : 'Not recorded'}</Fact><Fact label="Recorded AI state">{run?.status || 'No linked AI run'}</Fact><Fact label="Input tokens">{reportingNumber(usage.input)}</Fact><Fact label="Output tokens">{reportingNumber(usage.output)}</Fact><Fact label="AI recorded interval">{formatElapsed(evidence.aiIntervalMs)}</Fact><Fact label="Measured spend">Not recorded</Fact><Fact label="Saved reservation allowance">{reportingReservation(usage.reservation)}</Fact><Fact label="Linked email action">{action?.id || 'None verified'}</Fact><Fact label="Email action status">{action?.status || 'Not recorded'}</Fact><Fact label="Receipt phase">{receipt?.phase || 'Not recorded'}</Fact></dl>
    <p className="cor-muted">The AI interval runs from reservation to recorded result; it includes processing and is not model latency. The saved reservation is an admission-control allowance, not actual spend. Missing token or cost data is not zero.</p>
    {run?.failure_code && <p className="cor-warning">Recorded AI failure: {run.failure_code}</p>}
    <h4>Saved milestones</h4><p className="cor-muted">Timestamps from the current linked records. This is not a complete event log: earlier draft attempts and assignment changes are not returned by this view.</p>
    <ol className="cor-timeline">{evidence.events.map(event => <li key={event.key}><time dateTime={event.at}>{formatTime(event.at)}</time><div><strong>{event.label}</strong><p>{event.detail}</p></div></li>)}</ol>
    {evidence.undatedEvents.length > 0 && <details><summary>Records without timestamps ({evidence.undatedEvents.length})</summary><ul className="cor-undated">{evidence.undatedEvents.map(event => <li key={event.key}><strong>{event.label}</strong> · Time not recorded<p>{event.detail}</p></li>)}</ul></details>}
    <details><summary>Bound source references</summary>{workflow.context_version?.id === workflow.context_version_id && workflow.context_version?.organization_id === workflow.organization_id ? <p>Company reply context version {workflow.context_version.version} · {workflow.context_version.id}</p> : <p>No bound company context is available.</p>}{knowledgeUnavailable ? <p className="cor-warning">A knowledge source is no longer available. Its content and citations remain hidden.</p> : !(workflow.knowledge_sources || []).length ? <p>No Company Knowledge excerpts are bound to this attempt.</p> : <ul>{workflow.knowledge_sources.map(source => <li key={source.source_id}><strong>{source.title}</strong> · version {source.version}<p>Source: {source.source_id}</p><p>Content SHA-256: {source.content_sha256}</p><p>Version SHA-256: {source.version_sha256}</p><p>{run?.draft?.source_ids?.includes(source.source_id) ? 'Cited by the current saved draft' : 'Selected source; not cited by the current saved draft'}</p></li>)}</ul>}<p className="cor-muted">Source identity is evidence of provenance, not proof that every generated statement is correct.</p></details>
  </section>
}
