import React,{useEffect,useMemo,useRef,useState} from 'react'
import {buildWorkflowMonitor,formatElapsed,workflowRunCategory} from './workflow-monitor-data'
import {useWorkflowMonitor} from './use-workflow-monitor'
import './workflow-monitor.css'

const stamp=value=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString():'Not recorded'
const count=value=>Number.isFinite(value)?value:'—'
const rate=value=>Number.isFinite(value)?`${Math.round(value*100)}%`:'—'
const text=value=>typeof value==='string'&&value.trim()?value:'Not recorded'
function currentSelection(){const p=new URLSearchParams(window.location.search);return {workflowId:p.get('kairoWorkflow')||null,runId:p.get('kairoRun')||null,days:[7,30,90].includes(Number(p.get('kairoDays')))?Number(p.get('kairoDays')):30}}
function State({status}){return <span className={'wm-state wm-'+workflowRunCategory(status)}>{status||'Not recorded'}</span>}
function Stat({label,value,note}){return <div className="wm-stat"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function Facts({children}){return <dl className="wm-facts">{children}</dl>}
function Fact({label,children}){return <div><dt>{label}</dt><dd>{children}</dd></div>}

export default function WorkflowMonitor({organizationId,userId,definitions=[],schedules=[],agents=[],client,onManage}) {
  const [selection,setSelection]=useState(currentSelection),[days,setDays]=useState(()=>currentSelection().days),[search,setSearch]=useState(''),[filter,setFilter]=useState('All')
  const heading=useRef(null),runHeading=useRef(null),firstRender=useRef(true)
  const {workflowId,runId}=selection
  const telemetry=useWorkflowMonitor({client,organizationId,userId,workflowId,days})
  const model=useMemo(()=>buildWorkflowMonitor({organizationId,workflows:definitions,runs:telemetry.runs,agentRequests:telemetry.agentRequests,actions:telemetry.actions,schedules,days,now:telemetry.window?.end||Date.now()}),[organizationId,definitions,telemetry.runs,telemetry.agentRequests,telemetry.actions,schedules,days,telemetry.window?.end])
  useEffect(()=>{const sync=()=>{const next=currentSelection();setSelection(next);setDays(next.days)};window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync)},[])
  useEffect(()=>{if(firstRender.current){firstRender.current=false;return}heading.current?.focus()},[workflowId])
  useEffect(()=>{if(runId)runHeading.current?.focus()},[runId,telemetry.loading])
  function navigate(id,run=null,nextDays=days){const url=new URL(window.location.href);url.searchParams.set('kairoCompany',organizationId);url.searchParams.set('kairoDays',String(nextDays));if(id)url.searchParams.set('kairoWorkflow',id);else url.searchParams.delete('kairoWorkflow');if(run)url.searchParams.set('kairoRun',run);else url.searchParams.delete('kairoRun');window.history.pushState({},'',url.pathname+url.search+url.hash);setSelection({workflowId:id,runId:run,days:nextDays})}
  const selected=model.workflows.find(item=>item.workflow.id===workflowId)
  const metrics=selected?.metrics||model.totals
  const coverage=telemetry.coverage||{}
  const incomplete=coverage.runsTruncated||coverage.requestsTruncated||coverage.actionsTruncated
  const visible=model.workflows.filter(item=>(filter==='All'||item.workflow.status===filter)&&String(item.workflow.name||'Unnamed workflow').toLowerCase().includes(search.trim().toLowerCase()))
  const history=selected?[...selected.history].reverse():[]
  const selectedRun=history.find(row=>row.id===runId)
  const actualDefinition=definitions.find(w=>w.id===workflowId&&w.organization_id===organizationId)
  const currentSteps=Array.isArray(actualDefinition?.steps)?actualDefinition.steps:[]
  const runActions=selectedRun?(selected?.actions||[]).filter(a=>a.workflow_run_id===selectedRun.id):[]
  const runRequests=selectedRun?(selected?.agentRequests||[]).filter(a=>a.workflow_run_id===selectedRun.id):[]

  return <section className="wm-shell" aria-label="Workflow monitoring workspace" aria-busy={telemetry.loading}>
    <div className="wm-heading"><div><p className="wm-kicker">YOUR AI WORKFLOWS</p><h2 ref={heading} tabIndex={-1}>{workflowId?(selected?.workflow.name||'Workflow details'):'Workflow monitor'}</h2><p>See what ran, what needs attention, and how each workflow is performing.</p></div><div className="wm-heading-actions">{workflowId&&<button className="secondary" onClick={()=>navigate(null)}>← All workflows</button>}<button className="secondary" disabled={telemetry.loading} onClick={telemetry.refresh}>{telemetry.loading?'Refreshing…':'Refresh activity'}</button></div></div>
    <div className="wm-toolbar"><label>Reporting period<select value={days} onChange={e=>{const next=Number(e.target.value);setDays(next);navigate(workflowId,null,next)}}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label>{!workflowId&&<><label>Find a workflow<input type="search" placeholder="Search workflow names" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Configuration status<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Active','Draft','Paused','Retired'].map(s=><option key={s}>{s}</option>)}</select></label></>}<span className="wm-freshness">{telemetry.refreshedAt?`Updated ${stamp(telemetry.refreshedAt)}`:'Activity not loaded yet'}</span></div>
    <p className="wm-scope">Runs created in the selected UTC calendar-day window. {workflowId?'Up to the latest 200 runs for this workflow.':'Up to the latest 500 runs across this company; open a workflow for its own history.'} Refresh to load new activity.</p>
    {telemetry.loading&&<p className="wm-notice" role="status">Loading measured workflow activity…</p>}
    {telemetry.error&&<p className="wm-notice wm-warning" role="alert">{telemetry.error} Metrics are unavailable until the history can be read.</p>}
    {incomplete&&<p className="wm-notice wm-warning" role="status">This is a limited history sample. A record limit was reached; metrics describe loaded records only. Choose a shorter period{!workflowId?' or open a workflow':''} for a more focused view.</p>}
    {(coverage.requestsUnavailable||coverage.actionsUnavailable)&&!coverage.runsUnavailable&&<p className="wm-notice wm-warning" role="status">Some request or approval history is unavailable. Workflow outcomes remain visible; approval totals are incomplete.</p>}
    {!telemetry.loading&&workflowId&&!selected?<div className="wm-empty"><h3>Workflow unavailable in this company</h3><p>It may have been removed or belong to a different company. Return to the monitor to choose a workflow.</p><button className="secondary" onClick={()=>navigate(null)}>All workflows</button></div>:<>
      <div className="wm-stats"><Stat label="Recorded runs" value={telemetry.loading||coverage.runsUnavailable?'—':count(metrics?.totalRuns)} note="In loaded history"/><Stat label="Completed success rate" value={telemetry.loading||coverage.runsUnavailable?'—':rate(metrics?.successRate)} note={`${count(metrics?.terminalCount)} success/error outcomes; canceled excluded`}/><Stat label="Running / queued" value={telemetry.loading||coverage.runsUnavailable?'—':`${count(metrics?.activeCount)} / ${count(metrics?.queuedCount)}`} note="Recorded status, not a heartbeat"/><Stat label="Waiting for approval" value={telemetry.loading||coverage.runsUnavailable?'—':count(metrics?.waitingCount)} note="Workflow runs awaiting review"/></div>
      {!workflowId?<>
        <div className="wm-list-heading"><h3>{model.workflows.length} configured workflow{model.workflows.length===1?'':'s'}</h3><span>Open any workflow to explore its history</span></div>
        {!model.workflows.length?<div className="wm-empty"><h3>Your workflow workspace is ready</h3><p>Saved automations will appear here with their recorded runs, approvals and timing. There are no configured automations in this company yet.</p><p>Business workflow inventory entries are planning records. They appear here after a runnable workflow definition is created.</p>{onManage&&<button className="secondary" onClick={onManage}>Go to workflow setup</button>}</div>:!visible.length?<p className="wm-empty">No workflows match these filters.</p>:<div className="wm-workflows">{visible.map(item=><button className="wm-workflow" key={item.workflow.id} onClick={()=>navigate(item.workflow.id)}><div className="wm-workflow-name"><strong>{item.workflow.name}</strong><span>{item.workflow.description||'No description provided'}</span><small>{item.workflow.trigger_type||'Trigger not recorded'} · {count(item.workflow.stepCount)} configured steps</small></div><div><span className="wm-label">Configuration</span><b>{item.workflow.status||'Not recorded'}</b><span className="wm-label">Latest loaded outcome</span><State status={item.latestRun?.status}/></div><div><span className="wm-label">Recorded runs</span><b>{telemetry.loading||coverage.runsUnavailable?'—':item.metrics.totalRuns}</b><span className="wm-label">Completed success</span><b>{telemetry.loading||coverage.runsUnavailable?'—':rate(item.metrics.successRate)}</b></div><div className="wm-open"><span>{item.latestRun?stamp(item.latestRun.created_at):'No runs in loaded history'}</span><strong>View analytics →</strong></div></button>)}</div>}
      </>:selected&&!telemetry.loading&&!coverage.runsUnavailable&&<>
        <p className="wm-description">{selected.workflow.description||'No description provided'} <span className="wm-muted">Configuration: {selected.workflow.status} · Trigger: {selected.workflow.trigger_type}</span></p>
        <div className="wm-detail-grid"><div className="wm-box"><h3>Elapsed run time</h3><div className="wm-mini-grid"><Stat label="Average" value={formatElapsed(selected.metrics.duration.meanMs)}/><Stat label="Median (p50)" value={formatElapsed(selected.metrics.duration.p50Ms)}/><Stat label="p95" value={formatElapsed(selected.metrics.duration.p95Ms)}/></div><p className="wm-muted">{selected.metrics.duration.sampleCount} completed runs with valid start and finish timestamps. Elapsed time includes any time spent waiting for approval; it is not model latency.</p></div><div className="wm-box"><h3>Usage & cost</h3><div className="wm-mini-grid"><Stat label="Tokens / model usage" value="Not recorded"/><Stat label="Measured cost" value="Not recorded"/></div><p className="wm-muted">Current run records do not contain measured token or cost data. Configured budgets and planned savings are not actual spend.</p></div></div>
        <div className="wm-detail-grid"><div className="wm-box"><h3>Run volume & outcomes</h3><div className="wm-trend" role="img" aria-label={`Daily recorded run volume over ${days} UTC days; details in the table below`}>{selected.trend.map(day=>{const total=day.total??day.totalRuns??0,max=Math.max(1,...selected.trend.map(d=>d.total??d.totalRuns??0));return <div key={day.date} title={`${day.date}: ${total} runs`}><span style={{height:`${Math.max(total?4:0,total/max*90)}px`}}/><small>{day.date.slice(5)}</small></div>})}</div><details><summary>Daily counts (UTC)</summary><div className="wm-table-scroll"><table><thead><tr><th>Date</th><th>Runs</th><th>Success</th><th>Error</th><th>Waiting</th></tr></thead><tbody>{selected.trend.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.total??d.totalRuns??0}</td><td>{d.success??d.successCount??0}</td><td>{(d.errorCount||0)+(d.failedCount||0)}</td><td>{d.waiting??d.waitingCount??0}</td></tr>)}</tbody></table></div></details></div><div className="wm-box"><h3>Recorded status breakdown</h3><Facts>{Object.entries(selected.metrics.statusCounts||{}).map(([status,n])=><Fact key={status} label={status}>{n}</Fact>)}</Facts>{!selected.metrics.totalRuns&&<p className="wm-muted">No recorded runs in this loaded period.</p>}<p className="wm-muted">Queued, running, waiting and canceled runs are shown separately from successful or failed completion.</p></div></div>
        <div className="wm-box"><div className="wm-list-heading"><h3>Run history</h3><span>{history.length} loaded runs · newest first</span></div>{!history.length?<p className="wm-empty">{coverage.runsUnavailable?'Run history is unavailable.':'No runs recorded in this loaded period. A workflow can be configured without having run yet.'}</p>:<div className="wm-table-scroll"><table><thead><tr><th>Started / recorded</th><th>Recorded outcome</th><th>Elapsed</th><th>Summary</th><th>Details</th></tr></thead><tbody>{history.map(run=><tr key={run.id} className={run.id===runId?'wm-selected':''}><td>{stamp(run.started_at||run.created_at)}</td><td><State status={run.status}/></td><td>{formatElapsed(run.durationMs??run.elapsedMs)}</td><td>{run.summary||run.error_message||'No summary recorded'}</td><td><button className="secondary" aria-label={`View run from ${stamp(run.created_at)}`} onClick={()=>navigate(workflowId,run.id)}>View run</button></td></tr>)}</tbody></table></div>}</div>
        {runId&&!selectedRun&&!telemetry.loading&&<p className="wm-notice">This run is not in the loaded period or available history. Choose a longer period or another run.</p>}
        {selectedRun&&<section className="wm-box wm-run-detail" aria-label="Selected run details"><div className="wm-list-heading"><h3 ref={runHeading} tabIndex={-1}>Run details</h3><button className="secondary" onClick={()=>navigate(workflowId)}>Close run details</button></div><Facts><Fact label="Run ID">{selectedRun.id}</Fact><Fact label="Recorded outcome"><State status={selectedRun.status}/></Fact><Fact label="Started">{stamp(selectedRun.started_at)}</Fact><Fact label="Completed">{stamp(selectedRun.completed_at)}</Fact><Fact label="Elapsed">{formatElapsed(selectedRun.durationMs??selectedRun.elapsedMs)}</Fact><Fact label="Saved step marker">{Number.isInteger(selectedRun.current_step)?selectedRun.current_step:'Not recorded'}</Fact></Facts><p className="wm-muted">The saved step marker is a zero-based runtime position, not a count of completed steps. Per-step timing and a versioned step history are not recorded.</p><h4>Summary</h4><p className="wm-recorded-text">{text(selectedRun.summary)}</p><h4>Error details</h4><p className="wm-recorded-text">{text(selectedRun.error_message)}</p><h4>Approvals linked to this run</h4>{coverage.actionsUnavailable?<p>Approval history unavailable.</p>:!runActions.length?<p className="wm-muted">No approval requests are present in the loaded history for this run.</p>:runActions.map(a=><div className="wm-event" key={a.id}><strong>{a.title||a.action_type||'Action request'}</strong><span>Recorded status: {a.status} · Requested {stamp(a.created_at)}</span><span>Approved {stamp(a.approved_at)} · Executed {stamp(a.executed_at)} · Rejected {stamp(a.rejected_at)}</span>{a.error_message&&<p>{a.error_message}</p>}</div>)}<h4>Agent requests linked to this run</h4>{coverage.requestsUnavailable?<p>Agent request history unavailable.</p>:!runRequests.length?<p className="wm-muted">No linked agent requests in the loaded period.</p>:runRequests.map(r=><RequestRow key={r.id} request={r} agents={agents} outcome={selectedRun.status}/>)}<details><summary>Current workflow configuration ({currentSteps.length} steps)</summary><p className="wm-muted">This is the current definition; it may differ from the definition used for this historical run.</p><ol>{currentSteps.map((s,i)=><li key={i}>{typeof s?.type==='string'?s.type:'Step type not recorded'}</li>)}</ol></details></section>}
        <div className="wm-detail-grid"><div className="wm-box"><h3>Agent dispatch requests</h3><p className="wm-muted">A dispatched request is not proof that a workflow completed. The linked workflow run supplies its recorded outcome.</p>{coverage.requestsUnavailable?<p>Agent request history unavailable.</p>:!(selected.agentRequests||[]).length?<p className="wm-muted">No agent requests in the loaded period.</p>:(selected.agentRequests||[]).slice().reverse().map(r=><RequestRow key={r.id} request={r} agents={agents} outcome={history.find(x=>x.id===r.workflow_run_id)?.status}/>)}</div><div className="wm-box"><h3>Schedules</h3>{!(selected.schedules||[]).length?<p className="wm-muted">No schedule configured for this workflow.</p>:(selected.schedules||[]).map(s=><div className="wm-event" key={s.id}><strong>{s.name||'Workflow schedule'} · {s.active?'Active':'Paused'}</strong><span>Next due: {stamp(s.next_run_at)}</span><span>Last recorded dispatch: {stamp(s.last_run_at)}</span><span>{s.cron_expression||'Cadence not recorded'} · {s.timezone||'Timezone not recorded'}</span></div>)}<p className="wm-muted">Schedule timestamps describe dispatch scheduling; use run history to confirm execution results.</p></div></div>
      </>}
    </>}
  </section>
}
function RequestRow({request,agents,outcome}){return <div className="wm-event"><strong>{agents.find(a=>a.id===request.agent_id)?.name||'Agent request'}</strong><span>Request: {request.status==='Executed'?'Dispatched':request.status||'Not recorded'} · {stamp(request.created_at)}</span><span>Linked run: {outcome||'Outcome not in loaded history'}</span>{request.error_message&&<p>{request.error_message}</p>}</div>}
