-- Read-only minimum fresh-install preflight. Verify connector target suohuogalotxhsnkumvy separately.
select jsonb_build_object(
'postgres_version',current_setting('server_version'),
'counts',jsonb_build_object('oauth_connections',(select count(*) from public.oauth_connections),'action_requests',(select count(*) from public.action_requests),'agent_run_requests',(select count(*) from public.agent_run_requests),'workflow_runs',(select count(*) from public.workflow_runs),'integrations',(select count(*) from public.integrations)),
'new_table_collisions',(select coalesce(jsonb_agg(name),'[]') from unnest(array['private.microsoft_oauth_setups','public.action_execution_receipts','private.agent_daily_reservations','private.agent_run_reservations','public.ai_draft_configurations','public.ai_draft_runs']) name where to_regclass(name) is not null),
'new_column_collisions',(select coalesce(jsonb_agg(jsonb_build_object('table',table_name,'column',column_name)),'[]') from information_schema.columns where table_schema='public' and (table_name,column_name) in (values ('oauth_connections','oauth_verified_version'),('oauth_connections','oauth_revision'),('oauth_connections','oauth_refresh_revision'),('integrations','oauth_revision'),('action_requests','approval_guard_version'),('action_requests','approved_connection_binding'),('workflow_runs','workflow_revision'),('workflow_runs','workflow_steps'),('workflow_runs','workflow_context'),('workflow_runs','workflow_policy_snapshot'),('workflow_runs','agent_run_request_id'),('agent_run_requests','execution_snapshot'))),
'new_function_collisions',(select coalesce(jsonb_agg(n.nspname||'.'||p.proname),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.proname in ('agent_actor_allowed','agent_context_clean','agent_required_roles','ai_draft_authorize','ai_draft_finish','ai_draft_immutable','ai_draft_reserve','ai_draft_review','ai_draft_save','assert_agent_workflow_lineage','assert_workflow_action_approval','begin_microsoft_oauth_setup','build_agent_snapshot','claim_microsoft_action','claim_microsoft_oauth_setup','claim_workflow_continuation','commit_microsoft_refresh','complete_microsoft_oauth_setup','create_agent_workflow_request','create_trusted_workflow_run','fail_microsoft_oauth_setup','finish_agent_workflow','guard_agent_request','guard_agent_workflow_link','guard_execution_request','guard_microsoft_oauth_revision','guard_workflow_snapshot','microsoft_connection_binding','microsoft_grant_matches','reconcile_microsoft_attempt','record_microsoft_attempt','require_microsoft_setup_actor','reserve_agent_workflow','review_agent_workflow_request','rotate_microsoft_integration_revision','validate_microsoft_connection','workflow_policy_snapshot')),
'vault_wrappers',jsonb_build_object('read',to_regprocedure('public.edge_read_secret(uuid)')::text,'store',to_regprocedure('public.edge_store_secret(text,text,text)')::text,'update',to_regprocedure('public.edge_update_secret(uuid,text)')::text)
) as preflight;
